name: terraform-deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: prod
        type: choice
        options:
          - alpha
          - beta
          - prod
      aws-service:
        description: 'Terraform Working Directory'
        required: true
        default: 'ec2'
        type: string

jobs:
  terraform:
      name: "Terraform Action"
      runs-on: ubuntu-latest
      defaults:
      run:
        working-directory: ${{ inputs.stage }}/services/${{ inputs.aws-service }}
      steps:
        - name: Runner Checkout
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

        - name: Terraform Init
          id: tf_init
          # working-directory: ${{ inputs.stage }}/${{ inputs.aws-service }}
          run: |
            terraform init

        - name: Terraform Plan
          id: tf_plan
          # working-directory: ${{ inputs.stage }}/${{ inputs.aws-service }}
          run: |
            terraform plan
        
        - name: Terraform Apply
          id: tf_apply
          # working-directory: ${{ inputs.stage }}/${{ inputs.aws-service }}
          run: |
            terraform apply -auto-approve -input=false

          
